"""create rejected records table

Revision ID: 4664633764ac
Revises: 7005ac6097cb
Create Date: 2026-07-24 16:34:11.890151

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4664633764ac"
down_revision: str | Sequence[str] | None = "7005ac6097cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rejected_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_transaction_id", sa.Integer(), nullable=False),
        sa.Column(
            "rejection_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "rejected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_array_length(rejection_reasons) > 0",
            name="ck_rejected_records_has_reasons",
        ),
        sa.ForeignKeyConstraint(
            ["raw_transaction_id"],
            ["ingestion.raw_transactions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "raw_transaction_id", name="uq_rejected_records_raw_transaction"
        ),
        schema="ingestion",
    )
    op.create_index(
        op.f("ix_ingestion_rejected_records_raw_transaction_id"),
        "rejected_records",
        ["raw_transaction_id"],
        unique=False,
        schema="ingestion",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ingestion_rejected_records_raw_transaction_id"),
        table_name="rejected_records",
        schema="ingestion",
    )
    op.drop_table("rejected_records", schema="ingestion")
    # ### end Alembic commands ###
