"""create core accounts and transactions

Revision ID: 56c9489a66b2
Revises: 4664633764ac
Create Date: 2026-07-26 03:02:14.597570

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56c9489a66b2"
down_revision: str | Sequence[str] | None = "4664633764ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_system_id", sa.Integer(), nullable=False),
        sa.Column("external_account_id", sa.String(length=100), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("account_type", sa.String(length=30), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("opened_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency_code ~ '^[A-Z]{3}$'", name="ck_accounts_currency_code_format"
        ),
        sa.CheckConstraint(
            "status IS NULL OR status IN ('active', 'frozen', 'closed')",
            name="ck_accounts_status",
        ),
        sa.ForeignKeyConstraint(
            ["source_system_id"], ["ingestion.source_systems.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_system_id",
            "external_account_id",
            name="uq_accounts_source_external_id",
        ),
        schema="core",
    )
    op.create_index(
        op.f("ix_core_accounts_source_system_id"),
        "accounts",
        ["source_system_id"],
        unique=False,
        schema="core",
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_transaction_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("external_transaction_id", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transaction_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency_code ~ '^[A-Z]{3}$'", name="ck_transactions_currency_code_format"
        ),
        sa.CheckConstraint("amount > 0", name="ck_transactions_positive_amount"),
        sa.ForeignKeyConstraint(
            ["account_id"], ["core.accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["raw_transaction_id"],
            ["ingestion.raw_transactions.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id",
            "external_transaction_id",
            name="uq_transactions_account_external_id",
        ),
        sa.UniqueConstraint(
            "raw_transaction_id", name="uq_transactions_raw_transaction"
        ),
        schema="core",
    )
    op.create_index(
        op.f("ix_core_transactions_account_id"),
        "transactions",
        ["account_id"],
        unique=False,
        schema="core",
    )
    op.create_index(
        op.f("ix_core_transactions_raw_transaction_id"),
        "transactions",
        ["raw_transaction_id"],
        unique=False,
        schema="core",
    )
    op.create_index(
        op.f("ix_core_transactions_transaction_timestamp"),
        "transactions",
        ["transaction_timestamp"],
        unique=False,
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_core_transactions_transaction_timestamp"),
        table_name="transactions",
        schema="core",
    )
    op.drop_index(
        op.f("ix_core_transactions_raw_transaction_id"),
        table_name="transactions",
        schema="core",
    )
    op.drop_index(
        op.f("ix_core_transactions_account_id"),
        table_name="transactions",
        schema="core",
    )
    op.drop_table("transactions", schema="core")
    op.drop_index(
        op.f("ix_core_accounts_source_system_id"), table_name="accounts", schema="core"
    )
    op.drop_table("accounts", schema="core")
    # ### end Alembic commands ###
