"""allow duplicate raw transaction payloads

Revision ID: 7005ac6097cb
Revises: 8db49e4892cf
Create Date: 2026-07-23 15:25:12.523842

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7005ac6097cb"
down_revision: str | Sequence[str] | None = "8db49e4892cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_raw_transactions_run_fingerprint"),
        "raw_transactions",
        schema="ingestion",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_raw_transactions_run_fingerprint"),
        "raw_transactions",
        ["etl_run_id", "record_fingerprint"],
        schema="ingestion",
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
