"""create raw transactions table

Revision ID: 8db49e4892cf
Revises: db015d4f3d70
Create Date: 2026-07-22 23:42:45.686276

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8db49e4892cf"
down_revision: str | Sequence[str] | None = "db015d4f3d70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("etl_run_id", sa.Integer(), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=False),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("record_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_row_number > 0",
            name="ck_raw_transactions_positive_source_row_number",
        ),
        sa.ForeignKeyConstraint(
            ["etl_run_id"], ["ingestion.etl_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "etl_run_id",
            "record_fingerprint",
            name="uq_raw_transactions_run_fingerprint",
        ),
        sa.UniqueConstraint(
            "etl_run_id", "source_row_number", name="uq_raw_transactions_run_source_row"
        ),
        schema="ingestion",
    )
    op.create_index(
        op.f("ix_ingestion_raw_transactions_etl_run_id"),
        "raw_transactions",
        ["etl_run_id"],
        unique=False,
        schema="ingestion",
    )
    op.create_index(
        op.f("ix_ingestion_raw_transactions_record_fingerprint"),
        "raw_transactions",
        ["record_fingerprint"],
        unique=False,
        schema="ingestion",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ingestion_raw_transactions_record_fingerprint"),
        table_name="raw_transactions",
        schema="ingestion",
    )
    op.drop_index(
        op.f("ix_ingestion_raw_transactions_etl_run_id"),
        table_name="raw_transactions",
        schema="ingestion",
    )
    op.drop_table("raw_transactions", schema="ingestion")
    # ### end Alembic commands ###
