"""create risk alerts table

Revision ID: d22ee119ffee
Revises: 41762eda1a90
Create Date: 2026-08-03 21:29:17.529125

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d22ee119ffee"
down_revision: str | Sequence[str] | None = "41762eda1a90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_risk_result_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="open", nullable=False
        ),
        sa.Column("assigned_to", sa.String(length=100), nullable=True),
        sa.Column("resolution_outcome", sa.String(length=30), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "((status IN ('open', 'investigating') "
            "AND resolved_at IS NULL) OR "
            "(status IN ('resolved', 'dismissed') "
            "AND resolved_at IS NOT NULL))",
            name="ck_risk_alerts_resolution_timestamp",
        ),
        sa.CheckConstraint(
            "resolution_outcome IS NULL OR resolution_outcome "
            "IN ('confirmed_risk', 'false_positive', 'no_action')",
            name="ck_risk_alerts_resolution_outcome",
        ),
        sa.CheckConstraint(
            "status IN ('open', 'investigating', 'resolved', 'dismissed')",
            name="ck_risk_alerts_status",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_risk_result_id"],
            ["risk.transaction_risk_results.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "transaction_risk_result_id", name="uq_risk_alerts_transaction_risk_result"
        ),
        schema="risk",
    )
    op.create_index(
        op.f("ix_risk_risk_alerts_assigned_to"),
        "risk_alerts",
        ["assigned_to"],
        unique=False,
        schema="risk",
    )
    op.create_index(
        op.f("ix_risk_risk_alerts_status"),
        "risk_alerts",
        ["status"],
        unique=False,
        schema="risk",
    )
    op.create_index(
        op.f("ix_risk_risk_alerts_transaction_risk_result_id"),
        "risk_alerts",
        ["transaction_risk_result_id"],
        unique=False,
        schema="risk",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_risk_risk_alerts_transaction_risk_result_id"),
        table_name="risk_alerts",
        schema="risk",
    )
    op.drop_index(
        op.f("ix_risk_risk_alerts_status"), table_name="risk_alerts", schema="risk"
    )
    op.drop_index(
        op.f("ix_risk_risk_alerts_assigned_to"), table_name="risk_alerts", schema="risk"
    )
    op.drop_table("risk_alerts", schema="risk")
    # ### end Alembic commands ###
