"""create etl runs table

Revision ID: db015d4f3d70
Revises: 2c5b9e21f71d
Create Date: 2026-07-15 19:29:56.324428

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db015d4f3d70"
down_revision: str | Sequence[str] | None = "2c5b9e21f71d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "etl_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_system_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "extracted_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "accepted_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "rejected_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name="ck_etl_runs_status",
        ),
        sa.CheckConstraint(
            "extracted_count >= 0 AND accepted_count >= 0 AND rejected_count >= 0",
            name="ck_etl_runs_non_negative_counts",
        ),
        sa.ForeignKeyConstraint(
            ["source_system_id"], ["ingestion.source_systems.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="ingestion",
    )
    op.create_index(
        op.f("ix_ingestion_etl_runs_source_system_id"),
        "etl_runs",
        ["source_system_id"],
        unique=False,
        schema="ingestion",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ingestion_etl_runs_source_system_id"),
        table_name="etl_runs",
        schema="ingestion",
    )
    op.drop_table("etl_runs", schema="ingestion")
    # ### end Alembic commands ###
